apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: servanda-ingress
  namespace: servanda-office
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-connections: "10"
    nginx.ingress.kubernetes.io/limit-rpm: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - servanda.example.com
      secretName: servanda-tls
  rules:
    - host: servanda.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: servanda-api
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: servanda-web
                port:
                  number: 80
