apiVersion: apps/v1
kind: Deployment
metadata:
  name: servanda-api
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servanda-export-worker
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servanda-web
spec:
  replicas: 2
