apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: servanda-office

resources:
  - ../../prod
  - minio-statefulset.yaml
  - static-secrets.yaml

patches:
  - path: onprem-config-patch.yaml

commonLabels:
  environment: onprem
  deployment-type: onprem
