apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: servanda-office

resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - export-worker-deployment.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - network-policy-default-deny.yaml
  - network-policy-api.yaml
  - network-policy-worker.yaml
  - network-policy-web.yaml
  - backup-cronjob.yaml
  - backup-configmap.yaml
  - keycloak-backup-cronjob.yaml

commonLabels:
  app.kubernetes.io/part-of: servanda-office
