apiVersion: v1
kind: Service
metadata:
  name: {{ include "servanda-office.fullname" . }}-api
  namespace: {{ include "servanda-office.namespace" . }}
  labels:
    {{- include "servanda-office.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "servanda-office.api.selectorLabels" . | nindent 4 }}
