apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "servanda-office.configMapName" . }}
  namespace: {{ include "servanda-office.namespace" . }}
  labels:
    {{- include "servanda-office.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
  S3_BUCKET: {{ .Values.config.s3Bucket | quote }}
  FEATURE_ODT_EXPORT: {{ .Values.config.featureOdtExport | quote }}
  OIDC_ISSUER_URL: {{ .Values.config.oidcIssuerUrl | quote }}
