apiVersion: v1
kind: Service
metadata:
  name: {{ include "servanda-office.fullname" . }}-web
  namespace: {{ include "servanda-office.namespace" . }}
  labels:
    {{- include "servanda-office.web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "servanda-office.web.selectorLabels" . | nindent 4 }}
