apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: servanda-office

resources:
  - ../../base
  - sealed-secrets.yaml
  - cert-manager-issuer.yaml

patches:
  - path: namespace-patch.yaml
  - path: resource-patch.yaml

commonLabels:
  environment: staging
