apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: servanda-db-credentials
  namespace: servanda-office
spec:
  encryptedData:
    # Placeholder — seal with: kubeseal --format yaml < secret.yaml > sealed-secret.yaml
    url: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq...PLACEHOLDER
    username: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq...PLACEHOLDER
    password: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq...PLACEHOLDER
  template:
    metadata:
      name: servanda-db-credentials
      namespace: servanda-office
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: servanda-s3-credentials
  namespace: servanda-office
spec:
  encryptedData:
    # Placeholder — seal with: kubeseal --format yaml < secret.yaml > sealed-secret.yaml
    S3_ENDPOINT: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq...PLACEHOLDER
    S3_ACCESS_KEY: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq...PLACEHOLDER
    S3_SECRET_KEY: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq...PLACEHOLDER
  template:
    metadata:
      name: servanda-s3-credentials
      namespace: servanda-office
    type: Opaque
